name: Build and Deploy Jekyll Blog

on:
  push:
    branches: [main]

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        working-directory: ./blog
        run: bundle install

      - name: Build site
        working-directory: ./blog
        run: bundle exec jekyll build -d ../_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
